"""empty message

Revision ID: 862ba8f161c4
Revises: 37252fc14818
Create Date: 2023-02-06 23:00:39.618569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862ba8f161c4'
down_revision = '37252fc14818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], name=op.f('fk_article_author_id_author')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
